apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodrescue-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodrescue-frontend
  template:
    metadata:
      labels:
        app: foodrescue-frontend
    spec:
      containers:
        - name: frontend
          image: foodrescue-frontend:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
